name: microstructure-alpha-engine
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - pytest
  - websockets
  - python-binance
  - pip:
    - black
    - python-dotenv
    - pympler
    - tqdm
    - ipywidgets
    - statsmodels
    - pyarrow
    - black
    - -e .